USE [master]
GO
/****** Object:  Database [Mud]    Script Date: 11/02/2025 20:45:47 ******/
CREATE DATABASE [Mud]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Mud', FILENAME = N'd:\databases\Mud.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Mud_log', FILENAME = N'D:\Databases\Mud_log.ldf' , SIZE = 66560KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Mud].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Mud] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Mud] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Mud] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Mud] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Mud] SET ARITHABORT OFF 
GO
ALTER DATABASE [Mud] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Mud] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Mud] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Mud] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Mud] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Mud] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Mud] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Mud] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Mud] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Mud] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Mud] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Mud] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Mud] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Mud] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Mud] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Mud] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Mud] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Mud] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Mud] SET  MULTI_USER 
GO
ALTER DATABASE [Mud] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Mud] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Mud] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Mud] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Mud] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Mud', N'ON'
GO
ALTER DATABASE [Mud] SET QUERY_STORE = OFF
GO
USE [Mud]
GO
/****** Object:  Table [dbo].[Item]    Script Date: 11/02/2025 20:45:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Item](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[CreatedDate] [datetime2](7) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Description] [nvarchar](255) NOT NULL,
	[ItemType] [int] NOT NULL,
 CONSTRAINT [PK_Item] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Item] ADD  CONSTRAINT [DF_Item_CreatedDate]  DEFAULT (getdate()) FOR [CreatedDate]
GO
USE [master]
GO
ALTER DATABASE [Mud] SET  READ_WRITE 
GO
